from typing import Optional, List
from pydantic import BaseModel, Field

class Item(BaseModel):
    description: Optional[str] = Field(description="Item description")
    hts_number: Optional[str] = Field(description="HTS number")
    country_of_origin: Optional[str] = Field(description="Country of origin")

class BillOfLadingData(BaseModel):
    arrival_date: Optional[str] = Field(description="Arrival date")
    departure_date: Optional[str] = Field(description="departure date")
    reference_number: Optional[str] = Field(description="Reference Number")
    ocean_container_number: Optional[str] = Field(description="Ocean Container Number")
    voyage_number: Optional[str] = Field(description="Voyage Number")
    name_of_vessel: Optional[str] = Field(description="Name of Vessel")
    us_port_of_unlading: Optional[str] = Field(description="US port of unlading")
    foreign_port_of_lading: Optional[str] = Field(description="Foreign port of lading")
    master_bill_of_lading_number: Optional[str] = Field(description="Master Bill of Lading Number")
    ams_house_bill_of_lading_number: Optional[str] = Field(description="AMS House Bill of Lading Number")
    seller_name: Optional[str] = Field(description="Seller Name")
    seller_address: Optional[str] = Field(description="Seller Address")
    seller_city: Optional[str] = Field(description="Seller City")
    seller_state: Optional[str] = Field(description="Seller State")
    seller_country: Optional[str] = Field(description="Seller Country")
    seller_postal_code: Optional[str] = Field(description="Seller Postal Code")
    manufacturer_state: Optional[str] = Field(description="Manufacturer State")
    manufacturer_city: Optional[str] = Field(description="Manufacturer City")
    manufacturer_address: Optional[str] = Field(description="Manufacturer Address")
    manufacturer_name: Optional[str] = Field(description="Manufacturer Name")
    manufacturer_country: Optional[str] = Field(description="Manufacturer Country")
    manufacturer_zipcode: Optional[str] = Field(description="Manufacturer ZipCode")
    buyer_name: Optional[str] = Field(description="Buyer Name")
    buyer_address: Optional[str] = Field(description="Buyer Address")
    buyer_city: Optional[str] = Field(description="Buyer City")
    buyer_state: Optional[str] = Field(description="Buyer State")
    buyer_country: Optional[str] = Field(description="Buyer Country")
    buyer_zipcode: Optional[str] = Field(description="Buyer ZipCode")
    ship_to_name: Optional[str] = Field(description="Ship To Name")
    ship_to_address: Optional[str] = Field(description="Ship To Address")
    ship_to_city: Optional[str] = Field(description="Ship To City")
    ship_to_state: Optional[str] = Field(description="Ship To State")
    ship_to_country: Optional[str] = Field(description="Ship To Country")
    ship_to_postal_code: Optional[str] = Field(description="Ship To Postal Code")
    container_stuffing_name: Optional[str] = Field(description="Container Stuffing Name")
    container_stuffing_address: Optional[str] = Field(description="Container Stuffing Address")
    container_stuffing_city: Optional[str] = Field(description="Container Stuffing City")
    container_stuffing_state: Optional[str] = Field(description="Container Stuffing State")
    container_stuffing_country: Optional[str] = Field(description="Container Stuffing Country")
    container_stuffing_postal_code: Optional[str] = Field(description="Container Stuffing Postal Code")
    consolidator_name: Optional[str] = Field(description="Consolidator Name")
    consolidator_address: Optional[str] = Field(description="Consolidator Address")
    consolidator_city: Optional[str] = Field(description="Consolidator City")
    consolidator_state: Optional[str] = Field(description="Consolidator State")
    consolidator_country: Optional[str] = Field(description="Consolidator Country")
    consolidator_postal_code: Optional[str] = Field(description="Consolidator Postal Code")
    importer_of_record_name: Optional[str] = Field(description="Importer of Record Name")
    importer_of_record_address: Optional[str] = Field(description="Importer of Record Address")
    importer_of_record_city: Optional[str] = Field(description="Importer of Record City")
    importer_of_record_state: Optional[str] = Field(description="Importer of Record State")
    importer_of_record_country: Optional[str] = Field(description="Importer of Record Country")
    importer_of_record_postal_code: Optional[str] = Field(description="Importer of Record Postal Code")
    consignee_name: Optional[str] = Field(description="Consignee Name")
    consignee_address: Optional[str] = Field(description="Consignee Address")
    consignee_city: Optional[str] = Field(description="Consignee City")
    consignee_state: Optional[str] = Field(description="Consignee State")
    consignee_country: Optional[str] = Field(description="Consignee Country")
    consignee_postal_code: Optional[str] = Field(description="Consignee Postal Code")
    items: List[Item] = Field(default=[], description="List of items")