# Define the field mapping
field_mapping = {
    "arrival_date": "Arrival date",
    "departure_date": "departure date",
    "reference_number": "Reference Number",
    "ocean_container_number": "Ocean Container Number",
    "voyage_number": "Voyage Number",
    "name_of_vessel": "Name of Vessel",
    "us_port_of_unlading": "US port of unlading",
    "foreign_port_of_lading": "Foreign port of lading",
    "master_bill_of_lading_number": "Master Bill of Lading Number",
    "ams_house_bill_of_lading_number": "AMS House Bill of Lading Numbe",
    "seller_name": "Seller Name",
    "seller_address": "Seller Address",
    "seller_city": "Seller City",
    "seller_state": "Seller State",
    "seller_country": "Seller Country",
    "seller_postal_code": "Seller Postal Code",
    "manufacturer_state": "Manufacturer State",
    "manufacturer_city": "Manufacturer City",
    "manufacturer_address": "Manufacturer Address",
    "manufacturer_name": "Manufacturer Name",
    "manufacturer_country": "Manufacturer Country",
    "manufacturer_zipcode": "Manufacturer ZipCode",
    "buyer_name": "Buyer Name",
    "buyer_address": "Buyer Address",
    "buyer_city": "Buyer City",
    "buyer_state": "Buyer State",
    "buyer_country": "Buyer Country",
    "buyer_zipcode": "Buyer ZipCode",
    "ship_to_name": "Ship To Name",
    "ship_to_address": "Ship To Address",
    "ship_to_city": "Ship To City",
    "ship_to_state": "Ship To State",
    "ship_to_country": "Ship To Country",
    "ship_to_postal_code": "Ship To Postal Code",
    "container_stuffing_name": "Container Stuffing Name",
    "container_stuffing_address": "Container Stuffing Address",
    "container_stuffing_city": "Container Stuffing City",
    "container_stuffing_state": "Container Stuffing State",
    "container_stuffing_country": "Container Stuffing Country",
    "container_stuffing_postal_code": "Container Stuffing Postal Code",
    "consolidator_name": "Consolidator Name",
    "consolidator_address": "Consolidator Address",
    "consolidator_city": "Consolidator City",
    "consolidator_state": "Consolidator State",
    "consolidator_country": "Consolidator Country",
    "consolidator_postal_code": "Consolidator Postal Code",
    "importer_of_record_name": "Importer of Record Name",
    "importer_of_record_address": "Importer of Record Address",
    "importer_of_record_city": "Importer of Record City",
    "importer_of_record_state": "Importer of Record State",
    "importer_of_record_country": "Importer of Record Country",
    "importer_of_record_postal_code": "Importer of Record Postal Code",
    "consignee_name": "Consignee Name",
    "consignee_address": "Consignee Address",
    "consignee_city": "Consignee City",
    "consignee_state": "Consignee State",
    "consignee_country": "Consignee Country",
    "consignee_postal_code": "Consignee Postal Code"
}